FROM node:14.8.0 as build
WORKDIR /home/node/app
COPY package.json package-lock.json ./
RUN npm install 
COPY . .
RUN npm run build --prod

FROM nginx:1.19.2
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /home/node/app/dist/client /usr/share/nginx/html