version: '3.8'

services: 
  web:
    build: 
      context: ./src/client
      dockerfile: ../../support/Dockerfile.client
    ports: 
      - 8080:80
  api:
    build:
      context: ./src/api
      dockerfile: ../../support/Dockerfile.api
    ports:
      - 8888:80